name: aml-project
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.11.9
  - pip
  - pip:
      - river
      - mlflow
      - scikit-learn
      - xgboost
      - pandas
      - matplotlib
      - seaborn
      - jupyter
      - ipykernel
